{% set name = "graiax-silkcoder" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/graiax-silkcoder-{{ version }}.tar.gz
  sha256: b03fd19c5046210da8a017b2df7408d487792a3dcbe09b9049664c95c1ddbe37

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - pdm
    - python
  run:
    - imageio-ffmpeg
    - python

test:
  commands:
    - pip check
    - python -c "from graiax import silkcoder"
  requires:
    - pip

about:
  home: https://pypi.org/project/graiax-silkcoder/
  summary: transform audio file to silk
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'A simple silkv3 encoder'
  doc_url: https://github.com/I-love-study/graiax-silkcoder
  dev_url: https://github.com/I-love-study/graiax-silkcoder

extra:
  recipe-maintainers:
    - Wybxc
