{% set name = "graiax-silkcoder" %}
{% set version = "0.2.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/graiax-silkcoder-{{ version }}.tar.gz
  sha256: e9f5124e0f01a545b95e9a6beaf5d224beb3895fb3b93268b7c7d4af073f4061

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - pdm
    - python
  run:
    - imageio-ffmpeg
    - python

test:
  commands:
    - pip check
    - python -c "from graiax import silkcoder"
  requires:
    - pip

about:
  home: https://pypi.org/project/graiax-silkcoder/
  summary: transform audio file to silk
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'A simple silkv3 encoder'
  doc_url: https://github.com/I-love-study/graiax-silkcoder
  dev_url: https://github.com/I-love-study/graiax-silkcoder

extra:
  recipe-maintainers:
    - Wybxc
